//
//  MetadataCopyRenderer.swift
//  RetroRacing
//
//  Created by Dani Devesa on 25/06/2026.
//

import Foundation

public enum MetadataCopyRenderer {
    public static func render(catalog: MetadataCatalog) -> String {
        var lines = documentHeader(for: catalog)
        appendLocalizedMetadata(to: &lines, catalog: catalog)
        appendMetadataNotes(to: &lines)
        appendPromotionalText(to: &lines, catalog: catalog)
        appendLongCopy(
            to: &lines,
            heading: "Description Candidate",
            groups: groupedCopy(in: catalog, keyPath: \.description),
            limit: catalog.limits.descriptionCharacters
        )
        appendWhatsNew(to: &lines, catalog: catalog)
        lines.append(
            "_Generated by `swift run --package-path AppStore/scripts "
                + "generate-metadata-docs`._"
        )
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func documentHeader(
        for catalog: MetadataCatalog
    ) -> [String] {
        [
            "# Staged Metadata Copy",
            "",
            "Part of [App Store docs hub](../README.md).",
            "",
            "Last updated: \(catalog.lastUpdated)",
            "",
            "**Status:** version-localized fields are `DRAFT_APPLIED`; "
                + "shared name/subtitle fields are `BLOCKED`.",
            "",
            "**Canonical source:** "
                + "[metadata/retrorapid-v1.5.json]"
                + "(../metadata/retrorapid-v1.5.json). "
                + "Do not edit generated copy directly.",
            "",
            "**See also:** [Strategy](04-metadata-strategy.md) · "
                + "[Validation](12-validation-results.md) · "
                + "[Apply script](../scripts/README.md)",
            "",
            "---",
            "",
        ]
    }

    private static func appendLocalizedMetadata(
        to lines: inout [String],
        catalog: MetadataCatalog
    ) {
        lines += [
            "## Localized Metadata",
            "",
            "| Locale | App name | Name count | Subtitle | Subtitle count | "
                + "Keywords | Keyword bytes |",
            "|---|---|---:|---|---:|---|---:|",
        ]

        for locale in catalog.orderedLocales {
            let counts = MetadataCatalogValidator.counts(for: locale)
            lines.append(
                "| \(locale.code) | `\(locale.name)` | "
                    + "\(counts.nameCharacters)/\(catalog.limits.nameCharacters) | "
                    + "`\(locale.subtitle)` | "
                    + "\(counts.subtitleCharacters)/"
                    + "\(catalog.limits.subtitleCharacters) | "
                    + "`\(locale.keywords)` | "
                    + "\(counts.keywordBytes)/\(catalog.limits.keywordBytes) |"
            )
        }
        lines.append("")
    }

    private static func appendMetadataNotes(to lines: inout [String]) {
        lines += [
            "Notes:",
            "",
            "- App Store names use `RetroRapid:` while the installed app and "
                + "in-app UI retain `RetroRapid!` through `BrandMark`.",
            "- Subtitles explain the actual mechanic in readable language; hidden "
                + "keywords cover supporting search intents.",
            "- Apple Watch remains in promotional text, screenshots, and "
                + "descriptions instead of the subtitle.",
            "- English cross-localization splits subtitles and keywords across "
                + "`en-GB`/`en-AU` and `en-CA`/`en-US`.",
            "- Spanish offline intent uses `conexion` in `es-ES` and `internet` "
                + "in `es-MX`; full phrases remain in visible descriptions.",
            "- Re-run the generator after any catalog edit; UTF-8 keyword bytes "
                + "are validated automatically.",
            "",
        ]
    }

    private static func appendPromotionalText(
        to lines: inout [String],
        catalog: MetadataCatalog
    ) {
        lines += [
            "## Promotional Text",
            "",
            "| Locale | Promotional text | Count |",
            "|---|---|---:|",
        ]
        for group in groupedCopy(in: catalog, keyPath: \.promotionalText) {
            lines.append(
                "| \(group.locales.joined(separator: " / ")) | "
                    + "`\(group.copy)` | "
                    + "\(group.copy.count)/"
                    + "\(catalog.limits.promotionalTextCharacters) |"
            )
        }
        lines.append("")
    }

    private static func appendWhatsNew(
        to lines: inout [String],
        catalog: MetadataCatalog
    ) {
        lines += [
            "## What's New Candidate",
            "",
            "Use this shape for the next bug-fix or polish release if there is "
                + "no larger feature to lead with.",
            "",
        ]
        appendLongCopy(
            to: &lines,
            heading: nil,
            groups: groupedCopy(in: catalog, keyPath: \.whatsNew),
            limit: catalog.limits.whatsNewCharacters
        )
    }

    private static func appendLongCopy(
        to lines: inout [String],
        heading: String?,
        groups: [CopyGroup],
        limit: Int
    ) {
        if let heading {
            lines += ["## \(heading)", ""]
        }
        for group in groups {
            lines += [
                "### \(group.locales.joined(separator: " / "))",
                "",
                "```text",
                group.copy,
                "```",
                "",
                "Count: \(group.copy.count)/\(limit) characters.",
                "",
            ]
        }
    }

    private static func groupedCopy(
        in catalog: MetadataCatalog,
        keyPath: KeyPath<LocaleMetadata, String>
    ) -> [CopyGroup] {
        catalog.orderedLocales.reduce(into: [CopyGroup]()) { groups, locale in
            let copy = locale[keyPath: keyPath]
            if let index = groups.firstIndex(where: { $0.copy == copy }) {
                groups[index].locales.append(locale.code)
            } else {
                groups.append(CopyGroup(locales: [locale.code], copy: copy))
            }
        }
    }
}

private struct CopyGroup {
    var locales: [String]
    let copy: String
}
