//
//  MetadataValidationRenderer.swift
//  RetroRacing
//
//  Created by Dani Devesa on 25/06/2026.
//

import Foundation

public enum MetadataValidationRenderer {
    public static func render(catalog: MetadataCatalog) -> String {
        var lines = documentHeader(for: catalog)
        appendFieldStatuses(to: &lines, catalog: catalog)
        appendValidationTable(to: &lines, catalog: catalog)
        lines += [
            "",
            "All selected fields pass current Apple limits. Run "
                + "`swift run --package-path Scripts "
                + "generate-metadata-docs --check` before applying metadata or "
                + "submitting a release.",
            "",
            "_Generated by `swift run --package-path Scripts "
                + "generate-metadata-docs`._",
            "",
        ]
        return lines.joined(separator: "\n")
    }

    private static func documentHeader(
        for catalog: MetadataCatalog
    ) -> [String] {
        [
            "# Metadata Validation Results",
            "",
            "Part of [App Store docs hub](../README.md).",
            "",
            "Last updated: \(catalog.lastUpdated)",
            "",
            "**Status:** `READY` — the canonical catalog passes all configured "
                + "limits. Overall submission status: "
                + "`\(catalog.submissionStatus)`; see `03-submission-quality-gate.md` "
                + "for any remaining non-metadata blockers.",
            "",
            "**Canonical source:** "
                + "[metadata/retrorapid-v1.5.json]"
                + "(../metadata/retrorapid-v1.5.json).",
            "",
            "**See also:** [Metadata copy](05-metadata-copy.md) · "
                + "[Limits](01-limits-and-sources.md) · "
                + "[Submission gate](03-submission-quality-gate.md)",
            "",
            "---",
            "",
        ]
    }

    private static func appendFieldStatuses(
        to lines: inout [String],
        catalog: MetadataCatalog
    ) {
        lines += [
            "## Field Rollout Status",
            "",
            "| Field | Status |",
            "|---|---|",
        ]
        for field in fieldOrder {
            if let status = catalog.fieldStatuses[field] {
                lines.append("| \(fieldLabel(field)) | `\(status)` |")
            }
        }
        lines.append("")
    }

    private static func appendValidationTable(
        to lines: inout [String],
        catalog: MetadataCatalog
    ) {
        lines += [
            "## Validation Results",
            "",
            "Validated from the canonical catalog for version \(catalog.version). "
                + "Character counts use Swift `String.count`; keyword limits use "
                + "UTF-8 bytes.",
            "",
            "| Locale | App name | Subtitle | Promotional text | Keywords | "
                + "Keyword bytes | Description | What's New |",
            "|---|---:|---:|---:|---:|---:|---:|---:|",
        ]

        for locale in catalog.orderedLocales {
            let counts = MetadataCatalogValidator.counts(for: locale)
            lines.append(
                "| \(locale.code) | "
                    + "\(counts.nameCharacters)/\(catalog.limits.nameCharacters) | "
                    + "\(counts.subtitleCharacters)/"
                    + "\(catalog.limits.subtitleCharacters) | "
                    + "\(counts.promotionalTextCharacters)/"
                    + "\(catalog.limits.promotionalTextCharacters) | "
                    + "\(counts.keywordCharacters) chars | "
                    + "\(counts.keywordBytes)/\(catalog.limits.keywordBytes) | "
                    + "\(counts.descriptionCharacters)/"
                    + "\(catalog.limits.descriptionCharacters) | "
                    + "\(counts.whatsNewCharacters)/"
                    + "\(catalog.limits.whatsNewCharacters) |"
            )
        }
    }

    private static let fieldOrder = [
        "name",
        "subtitle",
        "keywords",
        "promotionalText",
        "description",
        "whatsNew",
    ]

    private static func fieldLabel(_ field: String) -> String {
        [
            "name": "Name",
            "subtitle": "Subtitle",
            "keywords": "Keywords",
            "promotionalText": "Promotional text",
            "description": "Description",
            "whatsNew": "What's New",
        ][field] ?? field
    }
}
